/**
 * Gate 4A0 greybox — hand-written TypeScript mirror of the projection shapes in
 * `docs/contracts/phase4a-api-contract.yaml`.
 *
 * These types are DELIBERATELY hand-written and DELIBERATELY temporary. Gate 4A2
 * replaces this file with `src/api/schema.d.ts`, generated by `openapi-typescript`
 * from the real FastAPI application's own `/openapi.json`. Adding that generator
 * is out of scope for Gate 4A0 (no new dependency may be installed), so the
 * greybox mirrors the sketch by hand instead.
 *
 * The point of the mirror is to prove, before any API exists, that every value
 * the twelve planned screens display can arrive as an explicit projection FIELD.
 * If a screen needed a number that is not declared here, that would be a
 * contract gap to report — not something to compute in the client.
 *
 * Nothing in this file, or anywhere under `src/greybox/`, performs simulation
 * arithmetic. Every displayed quantity is a literal in `fixture.ts`.
 */

/**
 * OPAQUE. The client echoes it verbatim on `/api/game/resolve` and never parses,
 * constructs, compares, or derives one. Typed as a branded-ish alias to make the
 * intent visible at every use site.
 */
export type Revision = string;

export type Tone = "positive" | "negative" | "caution" | "neutral";
export type Direction = "up" | "down" | "unchanged";
export type AlertSeverity = "critical" | "warning" | "info";
export type PolicySlotKind = "budget" | "amendment";
export type ProposalRoute = "legislative" | "decree";

export interface ConcernCard {
  label: string;
  /** Already formatted server-side, e.g. "60.00%". Never assembled here. */
  headline: string;
  /** Server-computed and pre-signed. The client never subtracts two values. */
  deltaText: string | null;
  direction: Direction;
  tone: Tone;
  detailScreen: ScreenId;
}

export interface CapitalSummary {
  current: number;
  capacity: number;
  committedThisTurn: number;
  /** Pre-formatted server-side, e.g. "500 / 1,000". */
  display: string;
}

export interface Alert {
  id: string;
  severity: AlertSeverity;
  headline: string;
  detail: string | null;
  screen: ScreenId | null;
}

export interface GoalCard {
  headline: string;
  detail: string | null;
}

export interface MapProjection {
  /** Always true in 4A. The engine has no province or region state at all. */
  presentationOnly: true;
  tintMetricLabel: string;
  tintValueBps: number;
  note: string;
}

export interface TerminalSummary {
  bucket: "victory" | "defeat";
  reasonLabel: string;
  turn: number;
  headline: string;
  retrospective: string[];
}

export interface InstitutionRow {
  label: string;
  loyaltyText: string;
  powerText: string;
  competenceText: string;
  corruptionText: string;
}

export interface BlocRow {
  partyId: string;
  blocId: string;
  displayName: string;
  seats: number;
  relationshipText: string;
  baselineText: string;
  disciplineText: string;
}

export interface ChamberRow {
  chamberId: string;
  displayName: string;
  totalSeats: number;
  governmentSeats: number;
  oppositionSeats: number;
  /** Present only where a vote actually occurred. */
  supportingSeats: number | null;
  requiredSeats: number | null;
}

export interface ConstitutionAxisRow {
  axis: string;
  currentLabel: string;
  amendable: boolean;
}

export interface BudgetLine {
  label: string;
  valueText: string;
  deltaText: string | null;
  direction: Direction;
}

export interface DashboardProjection {
  revision: Revision;
  turn: number;
  countryName: string;
  governmentForm: string;
  /** Server-rendered: "Turn 11", or "None scheduled". Never decided here. */
  nextElectionLabel: string;
  concerns: {
    money: ConcernCard;
    legitimacy: ConcernCard;
    legislature: ConcernCard;
    constitution: ConcernCard;
    survival: ConcernCard;
  };
  politicalCapital: CapitalSummary;
  /** Pre-ranked server-side; rendered in the order given. */
  alerts: Alert[];
  goal: GoalCard;
  map: MapProjection;
  terminal: TerminalSummary | null;
}

export interface RouteOption {
  route: ProposalRoute;
  available: boolean;
  /** Flat decree cost, or 0 for the legislative route. */
  capitalCost: number;
  costText: string;
}

export interface PolicySlotOption {
  kind: PolicySlotKind;
  label: string;
  available: boolean;
  unavailableReason: string | null;
  routes: RouteOption[];
}

export interface BlocOption {
  partyId: string;
  blocId: string;
  displayName: string;
  relationshipText: string;
  baselineText: string;
}

export interface DecisionOptionsProjection {
  revision: Revision;
  openingCapital: number;
  policySlot: {
    /** Budget and amendment are ONE mutually exclusive slot. */
    selected: PolicySlotKind | null;
    options: PolicySlotOption[];
  };
  relationshipInvestment: {
    perBlocMin: number;
    perBlocMax: number;
    blocs: BlocOption[];
  };
  /** Server-computed affordability. The client sums nothing to decide legality. */
  affordability: {
    committedText: string;
    openingText: string;
    /** Already-projected ratio; used for bar width only, never as a value. */
    committedRatioBps: number;
    affordable: boolean;
    verdictText: string;
  };
}

export interface DriverItem {
  /** One of the 30 stable reason IDs the engine already emits. */
  reasonId: string;
  label: string;
}

export interface LedgerEntry {
  label: string;
  target: string | null;
  amountText: string;
  effectText: string | null;
}

export interface TraceField {
  label: string;
  valueText: string;
  /** The report field this came from, e.g. "ElectionReport.final_support_bps". */
  sourceField: string;
}

/**
 * Defined ONCE, exactly as the contract sketch defines it once. The live Turn
 * Result screen and the History detail view render the SAME component over this
 * SAME type; their presentation logic is not duplicated.
 */
export interface TurnResultProjection {
  revision: Revision;
  turn: number;
  /** Layer 1 — one sentence, already rendered server-side. */
  outcomeHeadline: string;
  outcomeTone: Tone;
  /** Layer 2 — the reason IDs emitted that turn. */
  drivers: DriverItem[];
  ledger: LedgerEntry[];
  unchanged: string[];
  /** Layer 3 — exact values and the report fields they came from. */
  trace: TraceField[];
  terminal: TerminalSummary | null;
}

export interface HistoryListEntry {
  turn: number;
  outcomeLine: string;
  tone: Tone;
}

export interface ScenarioSummary {
  scenarioId: string;
  displayName: string;
  governmentForm: string;
  electionIntervalLabel: string;
  startingLegitimacyText: string;
  pitch: string;
  isShowcase: boolean;
}

export interface SaveSummary {
  saveId: string;
  displayName: string;
  scenarioId: string;
  currentTurn: number;
  updatedAt: string;
  terminalOutcomeSummary: string | null;
  loadable: boolean;
  integrityProblem: string | null;
}

/** The twelve planned screens. The registry pins this list exactly. */
export type ScreenId =
  | "title"
  | "dashboard"
  | "government"
  | "economy"
  | "legislature"
  | "constitution"
  | "relationships"
  | "decisions"
  | "result"
  | "history"
  | "terminal"
  | "glossary";

/**
 * The whole static greybox fixture. In Gate 4A2+ each of these arrives from its
 * own endpoint; here it is one frozen object with no behaviour.
 */
export interface GreyboxFixture {
  scenarios: ScenarioSummary[];
  saves: SaveSummary[];
  dashboard: DashboardProjection;
  decisionOptions: DecisionOptionsProjection;
  turnResult: TurnResultProjection;
  history: HistoryListEntry[];
  /** Keyed by turn; the History detail view reads one of these. */
  historyDetail: Record<number, TurnResultProjection>;
  government: {
    executiveLabel: string;
    selectionLabel: string;
    termLimitLabel: string;
    survivalHeadline: string;
    riskRows: { label: string; valueText: string; tone: Tone }[];
    institutions: InstitutionRow[];
  };
  economy: {
    treasuryText: string;
    balanceText: string;
    balanceDirection: Direction;
    revenue: BudgetLine[];
    spending: BudgetLine[];
  };
  legislature: {
    chambers: ChamberRow[];
    blocs: BlocRow[];
  };
  constitution: {
    digestText: string;
    amendmentDifficultyLabel: string;
    thresholdText: string;
    axes: ConstitutionAxisRow[];
  };
  relationships: BlocRow[];
  glossary: { term: string; definition: string }[];
  terminalOutcomes: {
    seed77: TerminalSummary;
    seed0: TerminalSummary;
  };
}
