/**
 * Gate 4A2 — Glossary. Chrome-level, not a registered navigation screen (see
 * `registry.ts`'s docstring); rendered by `GreyboxApp`'s persistent header
 * toggle.
 *
 * Hand-authored reference copy, not simulation data: definitions of terms the
 * engine already implements, carrying no numbers that could drift from the
 * engine's own values. Kept as a local constant rather than fetched, because
 * there is no reason a static glossary of already-shipped mechanics should
 * depend on the local server being reachable.
 */

import { Panel } from "../components";

const GLOSSARY_ENTRIES: readonly { term: string; definition: string }[] = [
  {
    term: "Political capital",
    definition:
      "The government's spendable political standing. It regenerates each turn up to a capacity, and is consumed whether a proposal passes or fails.",
  },
  {
    term: "Legitimacy",
    definition:
      "How far the population accepts the government's right to govern. It feeds election support and survival risk.",
  },
  {
    term: "Decree authority",
    definition:
      "A constitutional power to enact policy without a legislative vote, at a flat political-capital cost and a relationship penalty with every seated bloc.",
  },
  {
    term: "Transition pressure",
    definition:
      "Instability generated by changing the constitution. It rises when an amendment passes and decays on its own between amendments.",
  },
  {
    term: "Peaceful liberalization",
    definition:
      "The game's only victory: transition a noncompetitive constitution to a competitive one, then win the first election held under it.",
  },
  {
    term: "Revision",
    definition:
      "An opaque marker identifying the exact game state a screen was drawn from. The interface echoes it back when resolving, so a stale decision is refused rather than misapplied.",
  },
];

export function GlossaryScreen() {
  return (
    <div className="flex flex-col gap-6">
      <h2 className="font-[family-name:var(--font-display)] text-2xl text-parchment-100">
        Glossary
      </h2>
      <Panel title="Terms">
        <dl className="flex flex-col gap-3 text-sm">
          {GLOSSARY_ENTRIES.map((entry) => (
            <div key={entry.term}>
              <dt className="text-parchment-100">{entry.term}</dt>
              <dd className="text-parchment-200/80">{entry.definition}</dd>
            </div>
          ))}
        </dl>
      </Panel>
    </div>
  );
}
