/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/game/decision-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Decision Options
         * @description The legal-move envelope: what the client needs to build a decision.
         *
         *     Read-only, like `/game/state` -- captures `session.current_save` once and
         *     never takes the mutation boundary. Every figure is a real engine constant
         *     or a real state fact (frozen plan Sec 4.6, Sec 10); this endpoint decides
         *     nothing about what is affordable or legal to SUBMIT -- `/preview` scores a
         *     draft and `/resolve`'s own validators are still the only authority.
         */
        get: operations["get_decision_options_api_game_decision_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History
         * @description The timeline: one rendered line per resolved turn, nothing heavier.
         */
        get: operations["list_history_api_game_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/history/{turn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History Detail
         * @description One historical turn, rendered from its OWN stored report and state.
         *
         *     Nothing is recomputed from the current state: `entry_at(turn)` carries both
         *     the report written when that turn resolved and the state it produced, and
         *     `dashboardAsOfTurn` is built from the latter.
         */
        get: operations["get_history_detail_api_game_history__turn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Game
         * @description Load a save by ID.
         *
         *     The registry entry is never treated as proof of integrity: the save is read,
         *     parsed, version-checked and `validate_history`-checked, and only a save that
         *     passes all of that replaces the active session.
         */
        post: operations["load_game_api_game_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/map/strategic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategic Map
         * @description The read-only strategic map: theaters, directed routes and authored political shapes.
         *
         *     Read-only, like `/game/state` -- captures `session.current_save` once and never takes the
         *     mutation boundary. Presentation only: selecting a theater in the client queues nothing, and
         *     this endpoint never draws RNG, resolves a turn or writes state.
         */
        get: operations["get_strategic_map_api_game_map_strategic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Game
         * @description Start a campaign.
         *
         *     Order (ADR 0014): build the save, allocate a UUID, write it atomically,
         *     update the index, and only then swap the active session -- so the in-memory
         *     pointer never moves ahead of the disk.
         */
        post: operations["create_game_api_game_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Proposal
         * @description Score a drafted proposal without changing anything.
         *
         *     Deliberately does NOT take the mutation boundary: the frozen plan states
         *     preview uses "never the session lock, never a write", and taking it would let
         *     a player drafting in one tab reject an unrelated resolve in another.
         *
         *     Instead it captures `session.current_save` ONCE, at the top, and works
         *     entirely from that immutable reference -- so a concurrent resolve can never
         *     show preview a mixture of pre- and post-mutation state. It observes one
         *     complete revision or the other.
         */
        post: operations["preview_proposal_api_game_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve
         * @description Resolve one turn.
         *
         *     The order below is the authoritative one from ADR 0014, and the last two
         *     steps are the ones that are easy to get subtly wrong:
         *
         *       1. Acquire mutation admission immediately, or reject `resolution_in_progress`.
         *       2. Parse the client-echoed revision.
         *       3. Compare it with the live state; reject a stale revision.
         *       4. Build `DecisionSet` from the CLIENT's claimed turn/version, unsorted.
         *       5. Call the engine.
         *       6. Capture the returned immutable save in `new_save`.
         *       7. Persist `new_save` atomically.
         *       8. Swap `session.current_save` only after persistence succeeds.
         *       9. Release the boundary -- on every path, success or failure.
         *      10. Build the response from the CAPTURED `new_save`, never by re-reading
         *          `session.current_save` after the boundary is released, which another
         *          request could by then have advanced.
         *
         *     A persistence failure leaves both the in-memory save and the on-disk save
         *     exactly as they were.
         */
        post: operations["resolve_api_game_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/save-as": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save As
         * @description Checkpoint the current state under a NEW save id.
         *
         *     A branch, not a rename: the running session keeps autosaving under its
         *     original id, which is left untouched.
         */
        post: operations["save_as_api_game_save_as_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description The bare dashboard shape -- never a narrative about what changed.
         */
        get: operations["get_state_api_game_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Saves
         * @description Safe metadata only. No filesystem path ever appears in the response.
         */
        get: operations["list_saves_api_saves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Scenario cards for the Title screen.
         *
         *     Each file is actually loaded rather than described from a hand-written
         *     table, so the card can never claim a government form the scenario does not
         *     have.
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Detail */
            detail?: string | null;
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /** Screen */
            screen?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "warning" | "info";
        };
        /** BlocOption */
        BlocOption: {
            /** Bloc Id */
            bloc_id: string;
            /** Bloc Name */
            bloc_name: string;
            /** Chamber */
            chamber: string;
            /** Party Id */
            party_id: string;
            /** Party Name */
            party_name: string;
            /** Seats */
            seats: number;
        };
        /**
         * BudgetDecision
         * @description Set target tax rates and/or spending amounts for the upcoming turn.
         *
         *     Targets, not deltas: an omitted rate (`None`) leaves that rate at its
         *     current value; a rate that *is* included replaces it outright — even if
         *     the new value equals the old one, which is still an explicit, reportable
         *     player choice (`FinanceReport` labels it "unchanged" rather than treating
         *     it as if nothing was submitted; see `report.py`).
         *
         *     Must set at least one target: an empty decision that changes nothing is
         *     rejected at construction rather than silently accepted as a no-op that
         *     happens to do nothing (a *missing* `BudgetDecision` in a `DecisionSet` is
         *     how "keep the current budget" is actually expressed).
         *
         *     (Phase 3B1) `route` and `influence` extend this same decision rather than introducing a
         *     discriminated decision union yet (D5): the budget IS the one proposal 3B1 routes through a
         *     legislative vote or a decree, so there is no second decision kind yet for a union to
         *     discriminate. `route` defaults to `LEGISLATIVE` — a government must explicitly ask to bypass
         *     its chamber, never fall into doing so by omission. `influence` carries no stored total: the
         *     amount committed is always the exact sum of its allocations, so there is no second field that
         *     could ever disagree with the first.
         *
         *     None of the validators below can see `GameState`: whether a targeted bloc exists, whether the
         *     constitution actually permits the chosen route, and whether the government can afford the sum
         *     of every allocation are all resolution-time questions (slot 1) — an invalid decision aborts
         *     the whole turn atomically rather than partially applying (`simulation.legislature.
         *     LegislativeOutcome`'s docstring).
         */
        BudgetDecision: {
            /** Consumption Rate Bps */
            consumption_rate_bps?: number | null;
            /** Corporate Rate Bps */
            corporate_rate_bps?: number | null;
            /** Influence */
            influence?: components["schemas"]["InfluenceAllocation"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "budget";
            /** Personal Income Rate Bps */
            personal_income_rate_bps?: number | null;
            /** @default legislative */
            route: components["schemas"]["ProposalRoute"];
            /** Spending Updates */
            spending_updates?: components["schemas"]["SpendingUpdate"][];
        };
        /** CapitalSummary */
        CapitalSummary: {
            /** Capacity */
            capacity: number;
            /** Committed This Turn */
            committed_this_turn: number;
            /** Current */
            current: number;
            /** Display */
            display: string;
        };
        /**
         * ChamberPreview
         * @description One chamber's projected tally. Chambers are never pooled.
         */
        ChamberPreview: {
            /** Carries */
            carries: boolean;
            /** Chamber */
            chamber: string;
            /** Required Seats */
            required_seats: number;
            /** Supporting Seats */
            supporting_seats: number;
            /** Total Seats */
            total_seats: number;
        };
        /** ConcernCard */
        ConcernCard: {
            /** Delta Text */
            delta_text?: string | null;
            /** Detail Screen */
            detail_screen: string;
            /**
             * Direction
             * @default unchanged
             * @enum {string}
             */
            direction: "up" | "down" | "unchanged";
            /** Headline */
            headline: string;
            /** Label */
            label: string;
            /**
             * Tone
             * @default neutral
             * @enum {string}
             */
            tone: "positive" | "negative" | "caution" | "neutral";
        };
        /**
         * ConstitutionalAmendmentDecision
         * @description Propose one atomic amendment across one or more constitutional axes (Phase 3C).
         *
         *     This model validates only state-independent shape. Whether the selected route is legal,
         *     whether every target changes the opening constitution, whether the final combination remains
         *     coherent under C1-C10, and whether the political-capital commitment is affordable are all
         *     resolution-time checks in slot 1.
         */
        ConstitutionalAmendmentDecision: {
            /** Influence */
            influence?: components["schemas"]["InfluenceAllocation"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "constitutional_amendment";
            /** @default legislative */
            route: components["schemas"]["ProposalRoute"];
            /** Targets */
            targets: (components["schemas"]["DecreeAuthorityTarget"] | components["schemas"]["ExecutiveSystemTarget"] | components["schemas"]["ExecutiveSelectionTarget"] | components["schemas"]["ElectionIntervalTarget"] | components["schemas"]["TermLimitTarget"])[];
        };
        /** ConstitutionalAxisOption */
        ConstitutionalAxisOption: {
            /** Allowed Values */
            allowed_values?: string[] | null;
            /** Axis */
            axis: string;
            /** Current Value */
            current_value: string | number | null;
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
        };
        /** DashboardConcerns */
        DashboardConcerns: {
            constitution: components["schemas"]["ConcernCard"];
            legislature: components["schemas"]["ConcernCard"];
            legitimacy: components["schemas"]["ConcernCard"];
            money: components["schemas"]["ConcernCard"];
            survival: components["schemas"]["ConcernCard"];
        };
        /** DashboardProjection */
        DashboardProjection: {
            /**
             * Alerts
             * @default []
             */
            alerts: components["schemas"]["Alert"][];
            concerns: components["schemas"]["DashboardConcerns"];
            /** Country Name */
            country_name: string;
            goal: components["schemas"]["GoalCard"];
            /** Government Form */
            government_form: string;
            map: components["schemas"]["MapProjection"];
            /** Next Election Label */
            next_election_label: string;
            political_capital: components["schemas"]["CapitalSummary"];
            /** Revision */
            revision: string;
            terminal?: components["schemas"]["TerminalSummary"] | null;
            /** Turn */
            turn: number;
        };
        /**
         * DecisionOptionsProjection
         * @description Every REAL fact and constant needed to construct a legal decision.
         *
         *     Nothing here is invented: the bps and capital bounds are the engine's own
         *     strict types and constants (`StrictBps`, `RELATIONSHIP_INVESTMENT_CAP`,
         *     `DECREE_POLITICAL_CAPITAL_COST`, `CONSTITUTIONAL_AMENDMENT_DECREE_COST`),
         *     and the spending, bloc and constitutional-axis listings are read straight
         *     from state. This endpoint answers "what exists to choose from" -- it never
         *     scores a draft (`/preview` does that) and never decides legality on
         *     submission (`/resolve`'s own validators still do, authoritatively).
         *
         *     `policy_cards` is the Gate 4A3A game-loop projection: named, understood
         *     choices generated from this SAME state. It shares this envelope's
         *     `revision`, so a card catalog and the legal-move facts it was generated
         *     from are always the same age.
         */
        DecisionOptionsProjection: {
            /** Blocs */
            blocs: components["schemas"]["BlocOption"][];
            /** Chambers */
            chambers: string[];
            /** Constitutional Axes */
            constitutional_axes: components["schemas"]["ConstitutionalAxisOption"][];
            /** Decree Amendment Capital Cost */
            decree_amendment_capital_cost: number;
            /** Decree Available */
            decree_available: boolean;
            /** Decree Legislative Capital Cost */
            decree_legislative_capital_cost: number;
            /** Opening Capital */
            opening_capital: number;
            /**
             * Policy Cards
             * @default []
             */
            policy_cards: components["schemas"]["PolicyCard"][];
            /** Relationship Investment Maximum */
            relationship_investment_maximum: number;
            /** Relationship Investment Minimum */
            relationship_investment_minimum: number;
            /** Revision */
            revision: string;
            /** Spending Categories */
            spending_categories: components["schemas"]["SpendingCategoryOption"][];
            /** Tax Rate Bps Maximum */
            tax_rate_bps_maximum: number;
            /** Tax Rate Bps Minimum */
            tax_rate_bps_minimum: number;
        };
        /**
         * DecreeAuthority
         * @description Whether the executive may legislate unilaterally.
         * @enum {string}
         */
        DecreeAuthority: "none" | "emergency_only" | "unlimited";
        /**
         * DecreeAuthorityTarget
         * @description Replace the constitution's decree-authority axis.
         */
        DecreeAuthorityTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            axis: "decree_authority";
            value: components["schemas"]["DecreeAuthority"];
        };
        /** DriverItem */
        DriverItem: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Params */
            params?: {
                [key: string]: string | number;
            };
            /** Reason Id */
            reason_id: string;
        };
        /**
         * ElectionIntervalTarget
         * @description Replace or abolish the scheduled national-election interval.
         */
        ElectionIntervalTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            axis: "national_election_interval_turns";
            /** Value */
            value: number | null;
        };
        /**
         * ExecutiveSelection
         * @description How the executive comes to hold office.
         * @enum {string}
         */
        ExecutiveSelection: "direct_election" | "legislative_selection" | "hereditary" | "appointed";
        /**
         * ExecutiveSelectionTarget
         * @description Replace the constitution's executive-selection axis.
         */
        ExecutiveSelectionTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            axis: "executive_selection";
            value: components["schemas"]["ExecutiveSelection"];
        };
        /**
         * ExecutiveSystem
         * @description How the executive relates to the legislature.
         *
         *     **(R8)** `MONARCHICAL` exists because `PRESIDENTIAL + HEREDITARY` is incoherent: a presidential
         *     executive's defining feature is a separate origin from, and accountability distinct from, the
         *     legislature — a mandate or an appointment, never an inheritance. `MONARCHICAL` is the value that
         *     makes a hereditary (or elective) head of state honest, bound by C6/C7 below.
         * @enum {string}
         */
        ExecutiveSystem: "presidential" | "parliamentary" | "semi_presidential" | "monarchical";
        /**
         * ExecutiveSystemTarget
         * @description Replace the constitution's executive-system axis.
         */
        ExecutiveSystemTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            axis: "executive_system";
            value: components["schemas"]["ExecutiveSystem"];
        };
        /** GoalCard */
        GoalCard: {
            /** Detail */
            detail?: string | null;
            /** Headline */
            headline: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryDetailResponse
         * @description Shape B -- historical detail. Same `TurnResultProjection` type as Shape A.
         */
        HistoryDetailResponse: {
            dashboardAsOfTurn: components["schemas"]["DashboardProjection"];
            turnResult: components["schemas"]["TurnResultProjection"];
        };
        /** HistoryListEntry */
        HistoryListEntry: {
            /** Outcome Line */
            outcome_line: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "positive" | "negative" | "caution" | "neutral";
            /** Turn */
            turn: number;
        };
        /**
         * InfluenceAllocation
         * @description Political capital committed to one bloc, to move its vote (Phase 3B1).
         *
         *     Targets a bloc by `(party_id, bloc_id)` — the same pair `simulation.state` already uses to
         *     address a bloc globally (`LegislativeBlocState`'s docstring). Deliberately dumb about anything
         *     that needs `GameState` to answer: whether that bloc exists, whether the route even calls for
         *     whipping votes, and whether the government can afford the sum of every allocation are all
         *     resolution-time questions (slot 1), not construction-time ones.
         */
        InfluenceAllocation: {
            /** Bloc Id */
            bloc_id: string;
            /** Party Id */
            party_id: string;
            /** Political Capital */
            political_capital: number;
        };
        /** LedgerEntry */
        LedgerEntry: {
            /** Amount Text */
            amount_text: string;
            /** Effect Text */
            effect_text?: string | null;
            /** Label */
            label: string;
            /** Target */
            target?: string | null;
        };
        /** LoadRequest */
        LoadRequest: {
            /** Save Id */
            save_id: string;
        };
        /**
         * MapProjection
         * @description The dashboard's national-tint summary card -- a single colour value, not a map of
         *     anything. No theater, border or geometry lives here.
         *
         *     The real read-only strategic map (theaters, directed routes, authored political shapes) is a
         *     separate projection, `StrategicMapProjection` below, served at `GET /api/game/map/strategic`.
         *     Kept as a distinct type rather than folded together: this one is a dashboard summary widget,
         *     the other is a full spatial projection, and conflating them would make neither easy to reason
         *     about.
         */
        MapProjection: {
            /** Note */
            note: string;
            /**
             * Presentation Only
             * @default true
             * @constant
             */
            presentation_only: true;
            /** Tint Metric Label */
            tint_metric_label: string;
            /** Tint Value Bps */
            tint_value_bps: number;
        };
        /** NewGameRequest */
        NewGameRequest: {
            /** Scenario Id */
            scenario_id: string;
            /** Seed */
            seed?: number | null;
        };
        /** PolicyCard */
        PolicyCard: {
            /** Available */
            available: boolean;
            /** Card Id */
            card_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "taxation" | "spending" | "constitution" | "restraint";
            /** Category Label */
            category_label: string;
            /**
             * Clears Proposal Slot
             * @default false
             */
            clears_proposal_slot: boolean;
            /** Description */
            description: string;
            /** Diagnostic Code */
            diagnostic_code?: string | null;
            /**
             * Effects
             * @default []
             */
            effects: components["schemas"]["PolicyCardEffect"][];
            /**
             * Routes
             * @default []
             */
            routes: components["schemas"]["PolicyCardRoute"][];
            /** Title */
            title: string;
            /** Unavailable Detail */
            unavailable_detail?: string | null;
            /** Unavailable Reason */
            unavailable_reason?: ("route_constitutionally_unavailable" | "no_legislature" | "decree_cannot_amend_with_legislature" | "requires_companion_constitutional_change" | "outside_legal_bounds" | "no_baseline_to_scale" | "no_change_from_current" | "game_concluded") | null;
        };
        /** PolicyCardChamberRequirement */
        PolicyCardChamberRequirement: {
            /** Chamber */
            chamber: string;
            /** Required Seats */
            required_seats: number;
            /** Total Seats */
            total_seats: number;
        };
        /**
         * PolicyCardEffect
         * @description One "current -> proposed" fact about a card, in RAW typed form (R6).
         *
         *     No value here is preformatted ("20.00%", "200,000,000"): `current_value`/
         *     `proposed_value` are the raw bps/money/turn/term integers, `unit` names
         *     which format function in `src/format/**` applies, and `current_label`/
         *     `proposed_label` carry ONLY server-authored enum display text (there is no
         *     numeric formatting to do for an enum). React formats the raw values; it
         *     never invents or reformats a number itself.
         */
        PolicyCardEffect: {
            /** Current Label */
            current_label?: string | null;
            /** Current Value */
            current_value?: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "unchanged";
            /** Label */
            label: string;
            /** Proposed Label */
            proposed_label?: string | null;
            /** Proposed Value */
            proposed_value?: number | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "bps" | "money" | "turns" | "terms" | "enum";
        };
        /**
         * PolicyCardRoute
         * @description One route (legislative or decree) a card could be submitted through.
         *
         *     R11: no affordability field lives here. R2/R3: `template` is a real typed
         *     decision or `None` -- never a placeholder dict.
         */
        PolicyCardRoute: {
            /** Available */
            available: boolean;
            /** Bargaining Available */
            bargaining_available: boolean;
            /** Base Route Cost */
            base_route_cost: number;
            /**
             * Chambers
             * @default []
             */
            chambers: components["schemas"]["PolicyCardChamberRequirement"][];
            route: components["schemas"]["ProposalRoute"];
            /** Template */
            template?: (components["schemas"]["BudgetDecision"] | components["schemas"]["ConstitutionalAmendmentDecision"]) | null;
            /** Unavailable Detail */
            unavailable_detail?: string | null;
            /** Unavailable Reason */
            unavailable_reason?: ("route_constitutionally_unavailable" | "no_legislature" | "decree_cannot_amend_with_legislature" | "requires_companion_constitutional_change" | "outside_legal_bounds" | "no_baseline_to_scale" | "no_change_from_current" | "game_concluded") | null;
        };
        /**
         * PreviewProjection
         * @description A deterministic ESTIMATE, explicitly not an authoritative outcome.
         *
         *     `estimate` is always True and `excludes_stochastic_channels` names what the
         *     preview deliberately does not know, so no caller can mistake this for a
         *     resolved result.
         */
        PreviewProjection: {
            /**
             * Affordable
             * @default true
             */
            affordable: boolean;
            /**
             * Chambers
             * @default []
             */
            chambers: components["schemas"]["ChamberPreview"][];
            /**
             * Committed Capital
             * @default 0
             */
            committed_capital: number;
            /**
             * Estimate
             * @default true
             * @constant
             */
            estimate: true;
            /**
             * Excludes Stochastic Channels
             * @default []
             */
            excludes_stochastic_channels: string[];
            /**
             * Has Proposal
             * @default false
             */
            has_proposal: boolean;
            /**
             * Influence Capital
             * @default 0
             */
            influence_capital: number;
            /**
             * Investment Capital
             * @default 0
             */
            investment_capital: number;
            /**
             * Opening Capital
             * @default 0
             */
            opening_capital: number;
            /** Route */
            route?: string | null;
            /**
             * Route Capital Cost
             * @default 0
             */
            route_capital_cost: number;
            /**
             * Would Pass
             * @default false
             */
            would_pass: boolean;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /**
             * Decisions
             * @default []
             */
            decisions: {
                [key: string]: unknown;
            }[];
            /** Revision */
            revision: string;
        };
        /**
         * ProposalRoute
         * @description How the player asked for a proposal to become law.
         *
         *     Chosen explicitly per proposal, never inferred. A government that *could* rule by decree still
         *     has to say so, because bypassing a chamber is a deliberate act that later phases will attach
         *     consequences to (courts, legitimacy cost, constitutional crisis -- Phase 3C).
         * @enum {string}
         */
        ProposalRoute: "legislative" | "decree";
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Decisions
             * @default []
             */
            decisions: {
                [key: string]: unknown;
            }[];
            /** Revision */
            revision: string;
        };
        /**
         * ResolveResponse
         * @description Shape A -- live resolution. Envelope keys are camelCase per the contract.
         */
        ResolveResponse: {
            dashboard: components["schemas"]["DashboardProjection"];
            turnResult: components["schemas"]["TurnResultProjection"];
        };
        /** SaveAsRequest */
        SaveAsRequest: {
            /** Display Name */
            display_name: string;
        };
        /** SaveSummary */
        SaveSummary: {
            /** Current Turn */
            current_turn: number;
            /** Display Name */
            display_name: string;
            /** Integrity Problem */
            integrity_problem?: string | null;
            /**
             * Loadable
             * @default true
             */
            loadable: boolean;
            /** Save Id */
            save_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Terminal Outcome Summary */
            terminal_outcome_summary?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            /** Display Name */
            display_name: string;
            /** Election Interval Label */
            election_interval_label: string;
            /** Government Form */
            government_form: string;
            /** Is Showcase */
            is_showcase: boolean;
            /** Scenario Id */
            scenario_id: string;
            /** Starting Legitimacy Text */
            starting_legitimacy_text: string;
        };
        /**
         * SpendingCategory
         * @description The seven government spending categories modeled in Phase 2A (product spec §13).
         *
         *     Shared between `SpendingPlanState` (field names match these values exactly)
         *     and `simulation.decisions.SpendingUpdate` (a player's budget target for one
         *     category) — one enum, not two parallel category lists that could drift.
         * @enum {string}
         */
        SpendingCategory: "health" | "education" | "welfare" | "infrastructure" | "defense" | "security" | "administration";
        /** SpendingCategoryOption */
        SpendingCategoryOption: {
            /** Category */
            category: string;
            /** Current Amount */
            current_amount: number;
        };
        /**
         * SpendingUpdate
         * @description A player's target amount for one spending category.
         */
        SpendingUpdate: {
            /** Amount */
            amount: number;
            category: components["schemas"]["SpendingCategory"];
        };
        /**
         * StrategicMapProjection
         * @description The whole read-only strategic map (Strategic Military Map, Gate M0). Contains no order,
         *     no command, no pending action and no affordance for one.
         */
        StrategicMapProjection: {
            /** Capital Theater Id */
            capital_theater_id: string;
            /** Map Id */
            map_id: string;
            /** Routes */
            routes: components["schemas"]["StrategicRouteProjection"][];
            /** Shapes */
            shapes: components["schemas"]["StrategicShapeProjection"][];
            /** Theaters */
            theaters: components["schemas"]["StrategicTheaterProjection"][];
        };
        /**
         * StrategicRouteProjection
         * @description One DISPLAY edge (Strategic Military Map, Gate M0). Reciprocal directed pairs are
         *     collapsed into a single row so the map draws one line, never two overlapping ones.
         */
        StrategicRouteProjection: {
            /** Bidirectional */
            bidirectional: boolean;
            /** From Theater Id */
            from_theater_id: string;
            /** To Theater Id */
            to_theater_id: string;
        };
        /**
         * StrategicShapeProjection
         * @description One authored political outline (Strategic Military Map, Gate M0). Presentation only;
         *     never implies adjacency.
         */
        StrategicShapeProjection: {
            /** Owner Display Name */
            owner_display_name: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Owner Namespace
             * @enum {string}
             */
            owner_namespace: "player_country" | "foreign_profile";
            /** Polygon */
            polygon: [
                number,
                number
            ][];
            /** Shape Id */
            shape_id: string;
        };
        /**
         * StrategicTheaterProjection
         * @description One theater, fully resolved for display (Strategic Military Map, Gate M0). The client
         *     renders these fields and derives nothing: ownership, capital status and directed adjacency
         *     all arrive resolved.
         */
        StrategicTheaterProjection: {
            /** Centroid X */
            centroid_x: number;
            /** Centroid Y */
            centroid_y: number;
            /** Display Name */
            display_name: string;
            /** Incoming Theater Ids */
            incoming_theater_ids: string[];
            /** Is Capital */
            is_capital: boolean;
            /** Is Player Owned */
            is_player_owned: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "land" | "coastal";
            /**
             * Label Anchor
             * @enum {string}
             */
            label_anchor: "n" | "s" | "e" | "w" | "center";
            /** Outgoing Theater Ids */
            outgoing_theater_ids: string[];
            /** Owner Display Name */
            owner_display_name: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Owner Namespace
             * @enum {string}
             */
            owner_namespace: "player_country" | "foreign_profile";
            /** Theater Id */
            theater_id: string;
        };
        /**
         * TermLimitTarget
         * @description Replace or abolish the executive term limit.
         */
        TermLimitTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            axis: "executive_term_limit_terms";
            /** Value */
            value: number | null;
        };
        /** TerminalSummary */
        TerminalSummary: {
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "victory" | "defeat";
            /** Headline */
            headline: string;
            /** Reason Label */
            reason_label: string;
            /** Turn */
            turn: number;
        };
        /** TraceField */
        TraceField: {
            /** Label */
            label: string;
            /** Source Field */
            source_field: string;
            /** Value Text */
            value_text: string;
        };
        /** TurnResultProjection */
        TurnResultProjection: {
            /**
             * Drivers
             * @default []
             */
            drivers: components["schemas"]["DriverItem"][];
            /**
             * Ledger
             * @default []
             */
            ledger: components["schemas"]["LedgerEntry"][];
            /** Outcome Headline */
            outcome_headline: string;
            /**
             * Outcome Tone
             * @enum {string}
             */
            outcome_tone: "positive" | "negative" | "caution" | "neutral";
            /** Revision */
            revision: string;
            terminal?: components["schemas"]["TerminalSummary"] | null;
            /**
             * Trace
             * @default []
             */
            trace: components["schemas"]["TraceField"][];
            /** Turn */
            turn: number;
            /**
             * Unchanged
             * @default []
             */
            unchanged: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_decision_options_api_game_decision_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOptionsProjection"];
                };
            };
        };
    };
    list_history_api_game_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListEntry"][];
                };
            };
        };
    };
    get_history_detail_api_game_history__turn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_game_api_game_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategic_map_api_game_map_strategic_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategicMapProjection"];
                };
            };
        };
    };
    create_game_api_game_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_proposal_api_game_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_api_game_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_as_api_game_save_as_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_game_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProjection"];
                };
            };
        };
    };
    list_saves_api_saves_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveSummary"][];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
}
