/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/game/decision-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Decision Options
         * @description The legal-move envelope: what the client needs to build a decision.
         *
         *     Read-only, like `/game/state` -- captures `session.current_save` once and
         *     never takes the mutation boundary. Every figure is a real engine constant
         *     or a real state fact (frozen plan Sec 4.6, Sec 10); this endpoint decides
         *     nothing about what is affordable or legal to SUBMIT -- `/preview` scores a
         *     draft and `/resolve`'s own validators are still the only authority.
         */
        get: operations["get_decision_options_api_game_decision_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History
         * @description The timeline: one rendered line per resolved turn, nothing heavier.
         */
        get: operations["list_history_api_game_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/history/{turn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History Detail
         * @description One historical turn, rendered from its OWN stored report and state.
         *
         *     Nothing is recomputed from the current state: `entry_at(turn)` carries both
         *     the report written when that turn resolved and the state it produced, and
         *     `dashboardAsOfTurn` is built from the latter.
         */
        get: operations["get_history_detail_api_game_history__turn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Game
         * @description Load a save by ID.
         *
         *     The registry entry is never treated as proof of integrity: the save is read,
         *     parsed, version-checked and `validate_history`-checked, and only a save that
         *     passes all of that replaces the active session.
         */
        post: operations["load_game_api_game_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Game
         * @description Start a campaign.
         *
         *     Order (ADR 0014): build the save, allocate a UUID, write it atomically,
         *     update the index, and only then swap the active session -- so the in-memory
         *     pointer never moves ahead of the disk.
         */
        post: operations["create_game_api_game_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Proposal
         * @description Score a drafted proposal without changing anything.
         *
         *     Deliberately does NOT take the mutation boundary: the frozen plan states
         *     preview uses "never the session lock, never a write", and taking it would let
         *     a player drafting in one tab reject an unrelated resolve in another.
         *
         *     Instead it captures `session.current_save` ONCE, at the top, and works
         *     entirely from that immutable reference -- so a concurrent resolve can never
         *     show preview a mixture of pre- and post-mutation state. It observes one
         *     complete revision or the other.
         */
        post: operations["preview_proposal_api_game_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve
         * @description Resolve one turn.
         *
         *     The order below is the authoritative one from ADR 0014, and the last two
         *     steps are the ones that are easy to get subtly wrong:
         *
         *       1. Acquire mutation admission immediately, or reject `resolution_in_progress`.
         *       2. Parse the client-echoed revision.
         *       3. Compare it with the live state; reject a stale revision.
         *       4. Build `DecisionSet` from the CLIENT's claimed turn/version, unsorted.
         *       5. Call the engine.
         *       6. Capture the returned immutable save in `new_save`.
         *       7. Persist `new_save` atomically.
         *       8. Swap `session.current_save` only after persistence succeeds.
         *       9. Release the boundary -- on every path, success or failure.
         *      10. Build the response from the CAPTURED `new_save`, never by re-reading
         *          `session.current_save` after the boundary is released, which another
         *          request could by then have advanced.
         *
         *     A persistence failure leaves both the in-memory save and the on-disk save
         *     exactly as they were.
         */
        post: operations["resolve_api_game_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/save-as": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save As
         * @description Checkpoint the current state under a NEW save id.
         *
         *     A branch, not a rename: the running session keeps autosaving under its
         *     original id, which is left untouched.
         */
        post: operations["save_as_api_game_save_as_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description The bare dashboard shape -- never a narrative about what changed.
         */
        get: operations["get_state_api_game_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Saves
         * @description Safe metadata only. No filesystem path ever appears in the response.
         */
        get: operations["list_saves_api_saves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Scenario cards for the Title screen.
         *
         *     Each file is actually loaded rather than described from a hand-written
         *     table, so the card can never claim a government form the scenario does not
         *     have.
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Detail */
            detail?: string | null;
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /** Screen */
            screen?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "warning" | "info";
        };
        /** BlocOption */
        BlocOption: {
            /** Bloc Id */
            bloc_id: string;
            /** Bloc Name */
            bloc_name: string;
            /** Chamber */
            chamber: string;
            /** Party Id */
            party_id: string;
            /** Party Name */
            party_name: string;
            /** Seats */
            seats: number;
        };
        /** CapitalSummary */
        CapitalSummary: {
            /** Capacity */
            capacity: number;
            /** Committed This Turn */
            committed_this_turn: number;
            /** Current */
            current: number;
            /** Display */
            display: string;
        };
        /**
         * ChamberPreview
         * @description One chamber's projected tally. Chambers are never pooled.
         */
        ChamberPreview: {
            /** Carries */
            carries: boolean;
            /** Chamber */
            chamber: string;
            /** Required Seats */
            required_seats: number;
            /** Supporting Seats */
            supporting_seats: number;
            /** Total Seats */
            total_seats: number;
        };
        /** ConcernCard */
        ConcernCard: {
            /** Delta Text */
            delta_text?: string | null;
            /** Detail Screen */
            detail_screen: string;
            /**
             * Direction
             * @default unchanged
             * @enum {string}
             */
            direction: "up" | "down" | "unchanged";
            /** Headline */
            headline: string;
            /** Label */
            label: string;
            /**
             * Tone
             * @default neutral
             * @enum {string}
             */
            tone: "positive" | "negative" | "caution" | "neutral";
        };
        /** ConstitutionalAxisOption */
        ConstitutionalAxisOption: {
            /** Allowed Values */
            allowed_values?: string[] | null;
            /** Axis */
            axis: string;
            /** Current Value */
            current_value: string | number | null;
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
        };
        /** DashboardConcerns */
        DashboardConcerns: {
            constitution: components["schemas"]["ConcernCard"];
            legislature: components["schemas"]["ConcernCard"];
            legitimacy: components["schemas"]["ConcernCard"];
            money: components["schemas"]["ConcernCard"];
            survival: components["schemas"]["ConcernCard"];
        };
        /** DashboardProjection */
        DashboardProjection: {
            /**
             * Alerts
             * @default []
             */
            alerts: components["schemas"]["Alert"][];
            concerns: components["schemas"]["DashboardConcerns"];
            /** Country Name */
            country_name: string;
            goal: components["schemas"]["GoalCard"];
            /** Government Form */
            government_form: string;
            map: components["schemas"]["MapProjection"];
            /** Next Election Label */
            next_election_label: string;
            political_capital: components["schemas"]["CapitalSummary"];
            /** Revision */
            revision: string;
            terminal?: components["schemas"]["TerminalSummary"] | null;
            /** Turn */
            turn: number;
        };
        /**
         * DecisionOptionsProjection
         * @description Every REAL fact and constant needed to construct a legal decision.
         *
         *     Nothing here is invented: the bps and capital bounds are the engine's own
         *     strict types and constants (`StrictBps`, `RELATIONSHIP_INVESTMENT_CAP`,
         *     `DECREE_POLITICAL_CAPITAL_COST`, `CONSTITUTIONAL_AMENDMENT_DECREE_COST`),
         *     and the spending, bloc and constitutional-axis listings are read straight
         *     from state. This endpoint answers "what exists to choose from" -- it never
         *     scores a draft (`/preview` does that) and never decides legality on
         *     submission (`/resolve`'s own validators still do, authoritatively).
         */
        DecisionOptionsProjection: {
            /** Blocs */
            blocs: components["schemas"]["BlocOption"][];
            /** Chambers */
            chambers: string[];
            /** Constitutional Axes */
            constitutional_axes: components["schemas"]["ConstitutionalAxisOption"][];
            /** Decree Amendment Capital Cost */
            decree_amendment_capital_cost: number;
            /** Decree Available */
            decree_available: boolean;
            /** Decree Legislative Capital Cost */
            decree_legislative_capital_cost: number;
            /** Opening Capital */
            opening_capital: number;
            /** Relationship Investment Maximum */
            relationship_investment_maximum: number;
            /** Relationship Investment Minimum */
            relationship_investment_minimum: number;
            /** Revision */
            revision: string;
            /** Spending Categories */
            spending_categories: components["schemas"]["SpendingCategoryOption"][];
            /** Tax Rate Bps Maximum */
            tax_rate_bps_maximum: number;
            /** Tax Rate Bps Minimum */
            tax_rate_bps_minimum: number;
        };
        /** DriverItem */
        DriverItem: {
            /** Label */
            label: string;
            /** Params */
            params?: {
                [key: string]: string | number;
            };
            /** Reason Id */
            reason_id: string;
        };
        /** GoalCard */
        GoalCard: {
            /** Detail */
            detail?: string | null;
            /** Headline */
            headline: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryDetailResponse
         * @description Shape B -- historical detail. Same `TurnResultProjection` type as Shape A.
         */
        HistoryDetailResponse: {
            dashboardAsOfTurn: components["schemas"]["DashboardProjection"];
            turnResult: components["schemas"]["TurnResultProjection"];
        };
        /** HistoryListEntry */
        HistoryListEntry: {
            /** Outcome Line */
            outcome_line: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "positive" | "negative" | "caution" | "neutral";
            /** Turn */
            turn: number;
        };
        /** LedgerEntry */
        LedgerEntry: {
            /** Amount Text */
            amount_text: string;
            /** Effect Text */
            effect_text?: string | null;
            /** Label */
            label: string;
            /** Target */
            target?: string | null;
        };
        /** LoadRequest */
        LoadRequest: {
            /** Save Id */
            save_id: string;
        };
        /**
         * MapProjection
         * @description Presentation only. The engine has no province, region, or spatial state.
         */
        MapProjection: {
            /** Note */
            note: string;
            /**
             * Presentation Only
             * @default true
             * @constant
             */
            presentation_only: true;
            /** Tint Metric Label */
            tint_metric_label: string;
            /** Tint Value Bps */
            tint_value_bps: number;
        };
        /** NewGameRequest */
        NewGameRequest: {
            /** Scenario Id */
            scenario_id: string;
            /** Seed */
            seed?: number | null;
        };
        /**
         * PreviewProjection
         * @description A deterministic ESTIMATE, explicitly not an authoritative outcome.
         *
         *     `estimate` is always True and `excludes_stochastic_channels` names what the
         *     preview deliberately does not know, so no caller can mistake this for a
         *     resolved result.
         */
        PreviewProjection: {
            /**
             * Affordable
             * @default true
             */
            affordable: boolean;
            /**
             * Chambers
             * @default []
             */
            chambers: components["schemas"]["ChamberPreview"][];
            /**
             * Committed Capital
             * @default 0
             */
            committed_capital: number;
            /**
             * Estimate
             * @default true
             * @constant
             */
            estimate: true;
            /**
             * Excludes Stochastic Channels
             * @default []
             */
            excludes_stochastic_channels: string[];
            /**
             * Has Proposal
             * @default false
             */
            has_proposal: boolean;
            /**
             * Influence Capital
             * @default 0
             */
            influence_capital: number;
            /**
             * Investment Capital
             * @default 0
             */
            investment_capital: number;
            /**
             * Opening Capital
             * @default 0
             */
            opening_capital: number;
            /** Route */
            route?: string | null;
            /**
             * Route Capital Cost
             * @default 0
             */
            route_capital_cost: number;
            /**
             * Would Pass
             * @default false
             */
            would_pass: boolean;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /**
             * Decisions
             * @default []
             */
            decisions: {
                [key: string]: unknown;
            }[];
            /** Revision */
            revision: string;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Decisions
             * @default []
             */
            decisions: {
                [key: string]: unknown;
            }[];
            /** Revision */
            revision: string;
        };
        /**
         * ResolveResponse
         * @description Shape A -- live resolution. Envelope keys are camelCase per the contract.
         */
        ResolveResponse: {
            dashboard: components["schemas"]["DashboardProjection"];
            turnResult: components["schemas"]["TurnResultProjection"];
        };
        /** SaveAsRequest */
        SaveAsRequest: {
            /** Display Name */
            display_name: string;
        };
        /** SaveSummary */
        SaveSummary: {
            /** Current Turn */
            current_turn: number;
            /** Display Name */
            display_name: string;
            /** Integrity Problem */
            integrity_problem?: string | null;
            /**
             * Loadable
             * @default true
             */
            loadable: boolean;
            /** Save Id */
            save_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Terminal Outcome Summary */
            terminal_outcome_summary?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            /** Display Name */
            display_name: string;
            /** Election Interval Label */
            election_interval_label: string;
            /** Government Form */
            government_form: string;
            /** Is Showcase */
            is_showcase: boolean;
            /** Scenario Id */
            scenario_id: string;
            /** Starting Legitimacy Text */
            starting_legitimacy_text: string;
        };
        /** SpendingCategoryOption */
        SpendingCategoryOption: {
            /** Category */
            category: string;
            /** Current Amount */
            current_amount: number;
        };
        /** TerminalSummary */
        TerminalSummary: {
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "victory" | "defeat";
            /** Headline */
            headline: string;
            /** Reason Label */
            reason_label: string;
            /** Turn */
            turn: number;
        };
        /** TraceField */
        TraceField: {
            /** Label */
            label: string;
            /** Source Field */
            source_field: string;
            /** Value Text */
            value_text: string;
        };
        /** TurnResultProjection */
        TurnResultProjection: {
            /**
             * Drivers
             * @default []
             */
            drivers: components["schemas"]["DriverItem"][];
            /**
             * Ledger
             * @default []
             */
            ledger: components["schemas"]["LedgerEntry"][];
            /** Outcome Headline */
            outcome_headline: string;
            /**
             * Outcome Tone
             * @enum {string}
             */
            outcome_tone: "positive" | "negative" | "caution" | "neutral";
            /** Revision */
            revision: string;
            terminal?: components["schemas"]["TerminalSummary"] | null;
            /**
             * Trace
             * @default []
             */
            trace: components["schemas"]["TraceField"][];
            /** Turn */
            turn: number;
            /**
             * Unchanged
             * @default []
             */
            unchanged: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_decision_options_api_game_decision_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOptionsProjection"];
                };
            };
        };
    };
    list_history_api_game_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListEntry"][];
                };
            };
        };
    };
    get_history_detail_api_game_history__turn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_game_api_game_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_game_api_game_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_proposal_api_game_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_api_game_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_as_api_game_save_as_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_game_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardProjection"];
                };
            };
        };
    };
    list_saves_api_saves_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveSummary"][];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
}
