/**
 * Gate 4A2 — T-generated-types (part of R9), the sandbox-safe half.
 *
 * The REAL drift proof is a shell-level step (`npm run generate:api && git
 * diff --exit-code`), run as part of every verification pass -- this test
 * environment's child-process sandboxing makes `execFileSync`-based
 * regeneration unavailable from inside a vitest worker (confirmed: even
 * spawning `/bin/sh` itself returns ENOENT here), so a from-inside-vitest
 * regeneration test is not viable in this environment.
 *
 * What IS checkable from inside a test, and worth checking: the generator's
 * own "do not hand-edit" marker survives, and the file's shape is what
 * generation actually produces -- snake_case field names throughout, except
 * the three explicitly camelCase envelope keys the backend aliases
 * (`turnResult`, `dashboard`, `dashboardAsOfTurn`). A hand-edit that quietly
 * reintroduced the OLD greybox contract's camelCase field names (`deltaText`,
 * `countryName`, ...) would fail this.
 *
 * Reads the file as raw text via `import.meta.glob` (the same mechanism
 * `greybox/no-client-simulation.test.ts` uses) rather than `node:fs`, so this
 * needs no `@types/node` -- the project has never needed Node type
 * definitions, being a browser-only app, and this test does not become the
 * reason to add one.
 */

import { describe, expect, it } from "vitest";

const SCHEMA_MODULES: Record<string, string> = import.meta.glob("./schema.d.ts", {
  query: "?raw",
  import: "default",
  eager: true,
});
const SCHEMA_SOURCE = SCHEMA_MODULES["./schema.d.ts"];
if (SCHEMA_SOURCE === undefined) {
  throw new Error("schema.d.ts not found -- run `npm run generate:api` first");
}

describe("schema.d.ts is the untouched generated artifact", () => {
  it("carries openapi-typescript's own do-not-edit marker", () => {
    expect(SCHEMA_SOURCE).toContain("This file was auto-generated by openapi-typescript");
    expect(SCHEMA_SOURCE).toContain("Do not make direct changes to the file");
  });

  it("uses real snake_case field names, not the old greybox contract's camelCase", () => {
    // Real fields, confirmed present.
    for (const field of ["country_name", "delta_text", "government_form", "next_election_label"]) {
      expect(SCHEMA_SOURCE, `expected ${field} in the generated schema`).toContain(field);
    }
    // The old hand-written contract.ts's camelCase equivalents must be ABSENT
    // as field names (word-boundary matched, so this does not false-positive
    // on the three real camelCase envelope keys below).
    for (const oldField of ["countryName:", "deltaText:", "governmentForm:", "nextElectionLabel:"]) {
      expect(SCHEMA_SOURCE, `unexpected hand-written field ${oldField}`).not.toContain(oldField);
    }
  });

  it("keeps camelCase on exactly the three aliased envelope keys", () => {
    for (const envelopeKey of ["turnResult:", "dashboardAsOfTurn:"]) {
      expect(SCHEMA_SOURCE).toContain(envelopeKey);
    }
  });

  it("declares all eleven contract endpoints", () => {
    const paths = [
      "/api/scenarios",
      "/api/game/new",
      "/api/game/state",
      "/api/game/decision-options",
      "/api/game/preview",
      "/api/game/resolve",
      "/api/game/history",
      "/api/game/history/{turn}",
      "/api/saves",
      "/api/game/save-as",
      "/api/game/load",
    ];
    for (const p of paths) {
      expect(SCHEMA_SOURCE, `missing path ${p}`).toContain(`"${p}"`);
    }
  });
});
